#
# [ Database Configuration Section ]
#
logging:
  level:
    org.springframework.web.servlet: INFO
spring:
  datasource:
    platform: "postgis"
    driver-class-name: "org.postgis.DriverWrapper"
    url: "jdbc:postgresql_postGIS://localhost:5432/smyths"
    username: "smyths"
    password: "smyths"
  mvc:
      async:
      request-timeout: 1000000
server:
  port: 8880